name: flutter_platform_selector
description: platform selector.
version: 2.0.0
homepage: https://github.com/flutter-fast-kit/flutter_platform_selector

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
